### ISSUE TITLE
Typo or unexpected character in FormDataValidator.

### ISSUE THREAD

**Issue by zayats103** [sylvainlaurent/swagger-validator-maven-plugin#12]
I have got an error: Unexpected first character in the "`multipart/form-data" literal when trying to validate a swagger file with file parameter. 

https://github.com/sylvainlaurent/swagger-validator-maven-plugin/blob/72502859c17716027a511c0fbcd85fe4cfdc79ac/src/main/java/com/github/sylvainlaurent/maven/swaggervalidator/semantic/validator/path/FormDataValidator.java#L34

**Comment by sylvainlaurent** [comment]
good catch, fixed on master.
thanks @zayats103

**Comment by zayats103** [comment]
@sylvainlaurent Thanks for fast fix. Do you have any plans to release new version with this fix soon?
