### ISSUE TITLE
operationId must be unique over complete swagger.json

### ISSUE THREAD

**Issue by wrssmi** [sylvainlaurent/swagger-validator-maven-plugin#14]
Following check is not performed:
Each operation may specify a **unique** operationId.

see spec: https://swagger.io/docs/specification/2-0/paths-and-operations/

**Comment by giuliopulina** [comment]
@wrssmi I'm almost sure this check was performed, could you please provide an example?

**Comment by giuliopulina** [comment]
I see, currently the errors is raised only if the operation id is duplicated on the same path, not across all the paths in the doc. 
Need to think about best way to solve it.

**Comment by giuliopulina** [comment]
@sylvainlaurent I think that this issue can be closed too
