### ISSUE TITLE
Fixing NPE during ComposedModel validation in InheritanceChainPropertiesValidator

### ISSUE THREAD

**Issue by oyeli** [sylvainlaurent/swagger-validator-maven-plugin#16]
I had faced with NPE during validation Foo1 definition with InheritanceChainPropertiesValidator. composedModelWrapper.getChild().getProperties() throws NPE because composedModelWrapper.getChild() is null for Foo2 model

Model definitions to show inheritance hierarchy :
```
  Foo1:
    x-discriminator-value: value1
    allOf:
    - $ref: '#/definitions/Foo2'

  Foo2:
    allOf:
    - $ref: '#/definitions/Foo3'

  Foo3:
    allOf:
    - $ref: '#/definitions/Foo4'
    - type: object
      discriminator: prop1
      required:
      - prop1
      properties:
        prop1:
          $ref: '#/definitions/Foo3Type'

  Foo4:
    type: object
    properties:
      id:
        type: string

  Foo3Type:
    type: string
    enum:
    - value1
    - value2
    - value3

```

**Comment by oyeli** [comment]
I already have fix for this issue. I'm going to create PR.

**Comment by giuliopulina** [comment]
Hi @oyeli, could you please describe the use case to reproduce the error?

**Comment by oyeli** [comment]
Please, look at my PR https://github.com/sylvainlaurent/swagger-validator-maven-plugin/pull/17.

**Comment by oyeli** [comment]
> Hi @oyeli, could you please describe the use case to reproduce the error?

Yes, sure. I'll update description.

**Comment by kh0ma** [comment]
Hi @giuliopulina.

Today we also faced this issue after updating our normalizer library. It is highly recommended to fix it. Thanks.

**Comment by sylvainlaurent** [comment]
fixed by PR #17

**Comment by oyeli** [comment]
@sylvainlaurent could you please put the new version of the plugin to mvnrepository.com

**Comment by sylvainlaurent** [comment]
I deployed a 1.2.5 to maven central
