### ISSUE TITLE
configurable unique operationId 

### ISSUE THREAD

**Issue by oyeli** [sylvainlaurent/swagger-validator-maven-plugin#18]
@giuliopulina  @sylvainlaurent  I've updated plugin version from 1.2.2 to 1.2.4 and faced with problem that operationId now have to be unique over complete swagger.json (it was in issue #14). But it isn't correct for us. For example we have endpoints:
accounts/{id}/payments/{payment_id}/refunds 
payments/{payment_id}/refunds
on which we use the same operation getRefunds().
I propose to make it configurable. Which way do you think will be the best to solve this problem? For example we can add parameter to pom configuration to define the scope of check (path / all paths ...).
I will perform this changes.

**Comment by giuliopulina** [comment]
Hi @oyeli, 
Skipping this validation would be against the 2.0 specification: from https://swagger.io/specification/:

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. The operationId value is case-sensitive. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.

Is it possible for you to change just the operationId(s) to something like 'getRefundsForAccount' and 'getRefunds'?

**Comment by oyeli** [comment]
Thanks for clarification! Looks like we need to rename our operationIds to be unique.
