### ISSUE TITLE
Error with external references

### ISSUE THREAD

**Issue by giuliopulina** [sylvainlaurent/swagger-validator-maven-plugin#2]
Hello,

I'm trying to validate two specifications files in the same folder, like this:
* external-file.yaml
* swagger.yaml (references external-file.yaml -> $ref: './external-file.yaml#/definitions/Foo')

I'm getting this error while trying to validate swagger.yaml:

Execution validate of goal com.github.sylvainlaurent.maven:swagger-validator-maven-plugin:1.0.1:validate failed: Unable to load RELATIVE ref: ./external-file.yaml: Could not find ./external-file.yaml on the classpath.

Does the validator support this configuration?

Regards
Giulio

**Comment by sylvainlaurent** [comment]
thanks for your pr #3. Merged and release version 1.0.2 should appear to maven central in a couple of hours)

**Comment by giuliopulina** [comment]
Thanks to you for reviewing and merging, I checked and the new artifact version is available on maven central :)
